import numpy as np

aray1 = np.array([[6, 0, 9], [3, 7, 4], [5, 5, 5]])
aray2 = np.array([[5, 4, 9], [8, 3, 9], [6, 1, 9]])
aray3 = np.array([[3, 8, 2], [4, 5, 6], [7, 8, 9]])


print('\n\n\n\n\nAray = Array'.center(45, '*'))
print('\n\n\n\n')
print('Dotproduct method'.center(45, '-'))
dot = np.dot(aray1, aray2)
print('Dot prod of Aray1 and 2')
print(dot)
print()
dot = np.dot(aray2, aray3)
print('Dot prod of Aray2 and 3')
print(dot)
print()
dot = np.dot(aray1, aray3)
print('Dot prod of Array1 and 3')
print(dot)
print()

print('trans method'.center(45, '-'))
trans1 = aray1.transpose()
print()
print('Aray1 trans:')
print(trans1)
print()
trans2 = aray2.transpose()
print()
print('Aray1 trans:')
print(trans2)
print()
trans3 = aray3.transpose()
print()
print('Aray1 Transpose:')
print(trans3)
print()

print('Inverse method'.center(45, '-'))
inv1 = np.linalg.inv(aray1)
print()
print('Aray1 Inverse:')
print(inv1)
print()
inv2 = np.linalg.inv(aray2)
print()
print('Aray2 Inverse:')
print(inv2)
print()
inv3 = np.linalg.inv(aray3)
print()
print('Aray3 Inverse:')
print(inv3)
print()

print('Determinant method'.center(45, '-'))
det1 = np.linalg.det(aray1)
print()
print('Aray1 Determinant:')
print(det1)
print()
det2 = np.linalg.det(aray2)
print()
print('Aray2 Determinant:')
print(det2)
print()
det3 = np.linalg.det(aray3)
print()
print('Aray3 Determinant:')
print(det3)
print()

print('Flatten method'.center(45, '-'))
flatten1 = aray1.flatten()
print()
print('Aray1 Flat:')
print(flatten1)
print()
flatten2 = aray2.flatten()
print()
print('Aray2 Flat:')
print(flatten2)
print()
flatten3 = aray3.flatten()
print()
print('Aray3 Flat:')
print(flatten3)


